MasGlobal.Interview.TechnicalInterview/Controllers/GetEmployeesController.cs
namespace TechnicalInterview.Controllers
{
    using Dto;
    using MasGlobal.Interview.Interfaces;
    using System.Collections.Generic;
    using System.Web.Mvc;
    public class GetEmployeesController : Controller
    {
        IBlEmployees blEmployees;       
        public GetEmployeesController(IBlEmployees blEmployees)
        {
            this.blEmployees = blEmployees;     
        }
        // GET: GetEmployees
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetAllEmployees(int? id)
        {           
            List<DtoEmployees> lstEmployees = new List<DtoEmployees>();

            lstEmployees = this.blEmployees.GetEmployees(id);
            return Json(lstEmployees, JsonRequestBehavior.AllowGet);
        }
    }
}

MasGlobal.Interview.TechnicalInterview/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TechnicalInterview.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MasGlobal.Interview.TechnicalInterview/Views/GetEmployees/GetAllEmployees.cshtml
@{
    ViewBag.Title = "GetAllEmployees";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<script>
    function AddToCart(id) {
        $.ajax({
               url: '@Url.Action("GetAllEmployees", "GetEmployees")',
               type: 'GET',
               dataType: 'json',
               cache: false,
               data: { 'id': id },
               success: function (results) {
                    alert(results)
               },
               error: function () {
                alert('Error occured');
               }
       });
   }

</script>

<form role="form">
    <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" class="form-control" id="exampleInputEmail1"
               placeholder="Enter email">
    </div>
</form>

MasGlobal.Interview.TechnicalInterview/Views/GetEmployees/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Styles/MainCss.css" rel="stylesheet" />
<script src="~/Scripts/TechnicalTest/MainJavaScript.js"></script>

<form role="form">
    <div class="form-group">
        <h1>Technical Test</h1>
    </div>
    <div class="form-group">
        <label for="idEmployee">Id Employee</label>
        <input type="text" class="form-control"  onKeyPress="return OnlyNumbers(event)" id="txtIdEmployee"
               placeholder="Enter Id">
    </div>

    <div class="form-group">

        <button type="button" class="btn btn-primary" onclick="GetEmployees();">Search Employee</button>
    </div>
    <div>
        <table id="CustomGrid" class="display" style="width:100%"></table>
    </div>
</form>

MasGlobal.Interview.TechnicalInterview/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("https://code.jquery.com/jquery-3.3.1.js")

    @Scripts.Render("https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js")


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                
            </div>
          
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Technical Tech</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>